// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/oio-network/deeplx-extend/app/deeplx/internal/conf"
	"github.com/oio-network/deeplx-extend/app/deeplx/internal/server"
	"github.com/oio-network/deeplx-extend/app/deeplx/internal/service"
	"github.com/oio-network/deeplx-extend/app/deeplx/pkgs/client_pool"
	"github.com/oio-network/deeplx-extend/deeplx"
	"github.com/valyala/fasthttp"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confSecret *conf.Secret, logger log.Logger, clients ...*fasthttp.Client) (*kratos.App, func(), error) {
	translateService := deeplx.NewTranslateService(logger)
	clientPool, cleanup := client_pool.NewClientPool(clients...)
	deepLXService := service.NewDeepLXService(translateService, confSecret, clientPool, logger)
	httpServer := server.NewHTTPServer(confServer, deepLXService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
