server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
data:
  database:
    driver: mysql
    source: root:dangerous@tcp(127.0.0.1:3306)/deeplx?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password:
    db: 0
  cache:
    disable_client_cache: false
    ttl: 600s
  log:
    batch_write_size: 512
    batch_write_interval: 5s
    batch_write_timeout: 3s
secret:
  auth:
    token: homingso