// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessLogsColumns holds the columns for the "access_logs" table.
	AccessLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "ip", Type: field.TypeString},
		{Name: "country_name", Type: field.TypeString, Nullable: true},
		{Name: "country_code", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64, Nullable: true},
	}
	// AccessLogsTable holds the schema information for the "access_logs" table.
	AccessLogsTable = &schema.Table{
		Name:       "access_logs",
		Columns:    AccessLogsColumns,
		PrimaryKey: []*schema.Column{AccessLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "access_logs_users_access_logs",
				Columns:    []*schema.Column{AccessLogsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "token", Type: field.TypeUUID, Unique: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessLogsTable,
		UsersTable,
	}
)

func init() {
	AccessLogsTable.ForeignKeys[0].RefTable = UsersTable
}
