// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: deeplx/v1/access_log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AccessLogService_GetAccessLog_FullMethodName = "/deeplx.v1.AccessLogService/GetAccessLog"
)

// AccessLogServiceClient is the client API for AccessLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessLogServiceClient interface {
	GetAccessLog(ctx context.Context, in *GetGetAccessLogRequest, opts ...grpc.CallOption) (*AccessLog, error)
}

type accessLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessLogServiceClient(cc grpc.ClientConnInterface) AccessLogServiceClient {
	return &accessLogServiceClient{cc}
}

func (c *accessLogServiceClient) GetAccessLog(ctx context.Context, in *GetGetAccessLogRequest, opts ...grpc.CallOption) (*AccessLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessLog)
	err := c.cc.Invoke(ctx, AccessLogService_GetAccessLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessLogServiceServer is the server API for AccessLogService service.
// All implementations must embed UnimplementedAccessLogServiceServer
// for forward compatibility
type AccessLogServiceServer interface {
	GetAccessLog(context.Context, *GetGetAccessLogRequest) (*AccessLog, error)
	mustEmbedUnimplementedAccessLogServiceServer()
}

// UnimplementedAccessLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccessLogServiceServer struct {
}

func (UnimplementedAccessLogServiceServer) GetAccessLog(context.Context, *GetGetAccessLogRequest) (*AccessLog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessLog not implemented")
}
func (UnimplementedAccessLogServiceServer) mustEmbedUnimplementedAccessLogServiceServer() {}

// UnsafeAccessLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessLogServiceServer will
// result in compilation errors.
type UnsafeAccessLogServiceServer interface {
	mustEmbedUnimplementedAccessLogServiceServer()
}

func RegisterAccessLogServiceServer(s grpc.ServiceRegistrar, srv AccessLogServiceServer) {
	s.RegisterService(&AccessLogService_ServiceDesc, srv)
}

func _AccessLogService_GetAccessLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGetAccessLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessLogServiceServer).GetAccessLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessLogService_GetAccessLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessLogServiceServer).GetAccessLog(ctx, req.(*GetGetAccessLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessLogService_ServiceDesc is the grpc.ServiceDesc for AccessLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deeplx.v1.AccessLogService",
	HandlerType: (*AccessLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessLog",
			Handler:    _AccessLogService_GetAccessLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deeplx/v1/access_log.proto",
}
