// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             (unknown)
// source: deeplx/v1/access_log.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAccessLogServiceGetAccessLog = "/deeplx.v1.AccessLogService/GetAccessLog"

type AccessLogServiceHTTPServer interface {
	GetAccessLog(context.Context, *GetGetAccessLogRequest) (*AccessLog, error)
}

func RegisterAccessLogServiceHTTPServer(s *http.Server, srv AccessLogServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/access_logs/{id}", _AccessLogService_GetAccessLog0_HTTP_Handler(srv))
}

func _AccessLogService_GetAccessLog0_HTTP_Handler(srv AccessLogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGetAccessLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccessLogServiceGetAccessLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccessLog(ctx, req.(*GetGetAccessLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AccessLog)
		return ctx.Result(200, reply)
	}
}

type AccessLogServiceHTTPClient interface {
	GetAccessLog(ctx context.Context, req *GetGetAccessLogRequest, opts ...http.CallOption) (rsp *AccessLog, err error)
}

type AccessLogServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAccessLogServiceHTTPClient(client *http.Client) AccessLogServiceHTTPClient {
	return &AccessLogServiceHTTPClientImpl{client}
}

func (c *AccessLogServiceHTTPClientImpl) GetAccessLog(ctx context.Context, in *GetGetAccessLogRequest, opts ...http.CallOption) (*AccessLog, error) {
	var out AccessLog
	pattern := "/v1/access_logs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccessLogServiceGetAccessLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
