// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: deeplx/v1/types.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text                string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	RequestAlternatives int32  `protobuf:"varint,2,opt,name=requestAlternatives,proto3" json:"requestAlternatives,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetRequestAlternatives() int32 {
	if x != nil {
		return x.RequestAlternatives
	}
	return 0
}

type Lang struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceLangUserSelected string `protobuf:"bytes,1,opt,name=source_lang_user_selected,json=sourceLangUserSelected,proto3" json:"source_lang_user_selected,omitempty"`
	TargetLang             string `protobuf:"bytes,2,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
}

func (x *Lang) Reset() {
	*x = Lang{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lang) ProtoMessage() {}

func (x *Lang) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lang.ProtoReflect.Descriptor instead.
func (*Lang) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Lang) GetSourceLangUserSelected() string {
	if x != nil {
		return x.SourceLangUserSelected
	}
	return ""
}

func (x *Lang) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

type CommonJobParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WasSpoken       bool   `protobuf:"varint,1,opt,name=wasSpoken,proto3" json:"wasSpoken,omitempty"`
	TranscribeAs    string `protobuf:"bytes,2,opt,name=transcribe_as,json=transcribeAs,proto3" json:"transcribe_as,omitempty"`
	RegionalVariant string `protobuf:"bytes,3,opt,name=regionalVariant,proto3" json:"regionalVariant,omitempty"`
}

func (x *CommonJobParams) Reset() {
	*x = CommonJobParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonJobParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonJobParams) ProtoMessage() {}

func (x *CommonJobParams) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonJobParams.ProtoReflect.Descriptor instead.
func (*CommonJobParams) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *CommonJobParams) GetWasSpoken() bool {
	if x != nil {
		return x.WasSpoken
	}
	return false
}

func (x *CommonJobParams) GetTranscribeAs() string {
	if x != nil {
		return x.TranscribeAs
	}
	return ""
}

func (x *CommonJobParams) GetRegionalVariant() string {
	if x != nil {
		return x.RegionalVariant
	}
	return ""
}

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Texts           []*Text          `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Splitting       string           `protobuf:"bytes,2,opt,name=splitting,proto3" json:"splitting,omitempty"`
	Lang            *Lang            `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Timestamp       int64            `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CommonJobParams *CommonJobParams `protobuf:"bytes,5,opt,name=CommonJobParams,proto3" json:"CommonJobParams,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Params) GetTexts() []*Text {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *Params) GetSplitting() string {
	if x != nil {
		return x.Splitting
	}
	return ""
}

func (x *Params) GetLang() *Lang {
	if x != nil {
		return x.Lang
	}
	return nil
}

func (x *Params) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Params) GetCommonJobParams() *CommonJobParams {
	if x != nil {
		return x.CommonJobParams
	}
	return nil
}

type PostData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonrpc string  `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	Method  string  `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Id      int64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Params  *Params `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *PostData) Reset() {
	*x = PostData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostData) ProtoMessage() {}

func (x *PostData) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostData.ProtoReflect.Descriptor instead.
func (*PostData) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *PostData) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *PostData) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PostData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostData) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type TranslationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message      string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id           int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Data         string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Alternatives []string `protobuf:"bytes,5,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	SourceLang   string   `protobuf:"bytes,6,opt,name=source_lang,proto3" json:"source_lang,omitempty"`
	TargetLang   string   `protobuf:"bytes,7,opt,name=target_lang,proto3" json:"target_lang,omitempty"`
	Method       string   `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *TranslationResult) Reset() {
	*x = TranslationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationResult) ProtoMessage() {}

func (x *TranslationResult) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationResult.ProtoReflect.Descriptor instead.
func (*TranslationResult) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *TranslationResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TranslationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TranslationResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TranslationResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TranslationResult) GetAlternatives() []string {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *TranslationResult) GetSourceLang() string {
	if x != nil {
		return x.SourceLang
	}
	return ""
}

func (x *TranslationResult) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

func (x *TranslationResult) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type PayloadAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text       []string `protobuf:"bytes,1,rep,name=text,proto3" json:"text,omitempty"`
	TargetLang string   `protobuf:"bytes,2,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	SourceLang string   `protobuf:"bytes,3,opt,name=source_lang,json=sourceLang,proto3" json:"source_lang,omitempty"`
}

func (x *PayloadAPI) Reset() {
	*x = PayloadAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAPI) ProtoMessage() {}

func (x *PayloadAPI) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadAPI.ProtoReflect.Descriptor instead.
func (*PayloadAPI) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *PayloadAPI) GetText() []string {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *PayloadAPI) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

func (x *PayloadAPI) GetSourceLang() string {
	if x != nil {
		return x.SourceLang
	}
	return ""
}

type Translation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Translation) Reset() {
	*x = Translation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Translation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation) ProtoMessage() {}

func (x *Translation) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation.ProtoReflect.Descriptor instead.
func (*Translation) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Translation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranslationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translations []*Translation `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
}

func (x *TranslationResponse) Reset() {
	*x = TranslationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationResponse) ProtoMessage() {}

func (x *TranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationResponse.ProtoReflect.Descriptor instead.
func (*TranslationResponse) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *TranslationResponse) GetTranslations() []*Translation {
	if x != nil {
		return x.Translations
	}
	return nil
}

type DeepLUsageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterCount int32 `protobuf:"varint,1,opt,name=character_count,json=characterCount,proto3" json:"character_count,omitempty"`
	CharacterLimit int32 `protobuf:"varint,2,opt,name=character_limit,json=characterLimit,proto3" json:"character_limit,omitempty"`
}

func (x *DeepLUsageResponse) Reset() {
	*x = DeepLUsageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deeplx_v1_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeepLUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepLUsageResponse) ProtoMessage() {}

func (x *DeepLUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deeplx_v1_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepLUsageResponse.ProtoReflect.Descriptor instead.
func (*DeepLUsageResponse) Descriptor() ([]byte, []int) {
	return file_deeplx_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *DeepLUsageResponse) GetCharacterCount() int32 {
	if x != nil {
		return x.CharacterCount
	}
	return 0
}

func (x *DeepLUsageResponse) GetCharacterLimit() int32 {
	if x != nil {
		return x.CharacterLimit
	}
	return 0
}

var File_deeplx_v1_types_proto protoreflect.FileDescriptor

var file_deeplx_v1_types_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x78, 0x2e,
	0x76, 0x31, 0x22, 0x4c, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x30,
	0x0a, 0x13, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x22, 0x62, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x39, 0x0a, 0x19, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4c, 0x61, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x61,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4c, 0x61, 0x6e, 0x67, 0x22, 0x7e, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4a, 0x6f,
	0x62, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x61, 0x73, 0x53, 0x70,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x61, 0x73, 0x53,
	0x70, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x5f, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x22, 0xd6, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x25, 0x0a, 0x05, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x05, 0x74, 0x65, 0x78, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x6c, 0x69, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x61, 0x6e, 0x67, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x44, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x4a, 0x6f, 0x62, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0f, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x77, 0x0a,
	0x08, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x73, 0x6f,
	0x6e, 0x72, 0x70, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x73, 0x6f, 0x6e,
	0x72, 0x70, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x65,
	0x65, 0x70, 0x6c, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0xe5, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22,
	0x0a, 0x0c, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x61, 0x6e,
	0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x6c, 0x61, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c,
	0x61, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x62,
	0x0a, 0x0a, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x50, 0x49, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x6e,
	0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x61, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x61,
	0x6e, 0x67, 0x22, 0x21, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x51, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x65, 0x70, 0x6c, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x66, 0x0a, 0x12, 0x44, 0x65, 0x65, 0x70,
	0x4c, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x42, 0x39, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x69, 0x6f, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x64, 0x65, 0x65,
	0x70, 0x6c, 0x78, 0x2d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64,
	0x65, 0x65, 0x70, 0x6c, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_deeplx_v1_types_proto_rawDescOnce sync.Once
	file_deeplx_v1_types_proto_rawDescData = file_deeplx_v1_types_proto_rawDesc
)

func file_deeplx_v1_types_proto_rawDescGZIP() []byte {
	file_deeplx_v1_types_proto_rawDescOnce.Do(func() {
		file_deeplx_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_deeplx_v1_types_proto_rawDescData)
	})
	return file_deeplx_v1_types_proto_rawDescData
}

var file_deeplx_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_deeplx_v1_types_proto_goTypes = []any{
	(*Text)(nil),                // 0: deeplx.v1.Text
	(*Lang)(nil),                // 1: deeplx.v1.Lang
	(*CommonJobParams)(nil),     // 2: deeplx.v1.CommonJobParams
	(*Params)(nil),              // 3: deeplx.v1.Params
	(*PostData)(nil),            // 4: deeplx.v1.PostData
	(*TranslationResult)(nil),   // 5: deeplx.v1.TranslationResult
	(*PayloadAPI)(nil),          // 6: deeplx.v1.PayloadAPI
	(*Translation)(nil),         // 7: deeplx.v1.Translation
	(*TranslationResponse)(nil), // 8: deeplx.v1.TranslationResponse
	(*DeepLUsageResponse)(nil),  // 9: deeplx.v1.DeepLUsageResponse
}
var file_deeplx_v1_types_proto_depIdxs = []int32{
	0, // 0: deeplx.v1.Params.texts:type_name -> deeplx.v1.Text
	1, // 1: deeplx.v1.Params.lang:type_name -> deeplx.v1.Lang
	2, // 2: deeplx.v1.Params.CommonJobParams:type_name -> deeplx.v1.CommonJobParams
	3, // 3: deeplx.v1.PostData.params:type_name -> deeplx.v1.Params
	7, // 4: deeplx.v1.TranslationResponse.translations:type_name -> deeplx.v1.Translation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_deeplx_v1_types_proto_init() }
func file_deeplx_v1_types_proto_init() {
	if File_deeplx_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deeplx_v1_types_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Lang); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CommonJobParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PostData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TranslationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PayloadAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Translation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*TranslationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deeplx_v1_types_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeepLUsageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deeplx_v1_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deeplx_v1_types_proto_goTypes,
		DependencyIndexes: file_deeplx_v1_types_proto_depIdxs,
		MessageInfos:      file_deeplx_v1_types_proto_msgTypes,
	}.Build()
	File_deeplx_v1_types_proto = out.File
	file_deeplx_v1_types_proto_rawDesc = nil
	file_deeplx_v1_types_proto_goTypes = nil
	file_deeplx_v1_types_proto_depIdxs = nil
}
